/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  address?: string;
  city?: string;
  phone?: string;
  email?: string;
  facebook?: string;
  instagram?: string;
  heroImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  mainImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  body?: BlockContent;
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h2" | "h3" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
      _key: string;
    }
>;

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Horse = {
  _id: string;
  _type: "horse";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  breed?: string;
  birthYear?: number;
  status?: "active" | "retired" | "forSale";
  mainImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  description?: BlockContent;
  photos?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  sire?: string;
  dam?: string;
  milestones?: Array<{
    year?: number;
    event?: string;
    _key: string;
  }>;
  videos?: Array<{
    title?: string;
    url?: string;
    _key: string;
  }>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SiteSettings
  | SanityImageCrop
  | SanityImageHotspot
  | Page
  | BlockContent
  | Slug
  | Horse
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: src/sanity/lib/queries.ts
// Variable: horsesQuery
// Query: *[_type == "horse"] | order(name asc) {    _id,    name,    slug,    breed,    birthYear,    status,    mainImage  }
export type HorsesQueryResult = Array<{
  _id: string;
  name: string | null;
  slug: Slug | null;
  breed: string | null;
  birthYear: number | null;
  status: "active" | "forSale" | "retired" | null;
  mainImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: horseBySlugQuery
// Query: *[_type == "horse" && slug.current == $slug][0] {    _id,    name,    slug,    breed,    birthYear,    status,    mainImage,    description,    sire,    dam,    milestones,    photos,    videos  }
export type HorseBySlugQueryResult = {
  _id: string;
  name: string | null;
  slug: Slug | null;
  breed: string | null;
  birthYear: number | null;
  status: "active" | "forSale" | "retired" | null;
  mainImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  description: BlockContent | null;
  sire: string | null;
  dam: string | null;
  milestones: Array<{
    year?: number;
    event?: string;
    _key: string;
  }> | null;
  photos: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }> | null;
  videos: Array<{
    title?: string;
    url?: string;
    _key: string;
  }> | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: horsesSlugsQuery
// Query: *[_type == "horse" && defined(slug.current)] {    "slug": slug.current  }
export type HorsesSlugsQueryResult = Array<{
  slug: string | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: featuredHorsesQuery
// Query: *[_type == "horse" && status == "active"] | order(name asc) [0...3] {    _id,    name,    slug,    breed,    mainImage  }
export type FeaturedHorsesQueryResult = Array<{
  _id: string;
  name: string | null;
  slug: Slug | null;
  breed: string | null;
  mainImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: siteSettingsQuery
// Query: *[_type == "siteSettings"][0] {    address,    city,    phone,    email,    facebook,    instagram,    heroImage  }
export type SiteSettingsQueryResult = {
  address: string | null;
  city: string | null;
  phone: string | null;
  email: string | null;
  facebook: string | null;
  instagram: string | null;
  heroImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: galleryQuery
// Query: *[_type == "horse" && defined(photos) && count(photos) > 0] | order(name asc) {    name,    "slug": slug.current,    "photos": photos[] {      _key,      alt,      asset    }  }
export type GalleryQueryResult = Array<{
  name: string | null;
  slug: string | null;
  photos: Array<{
    _key: string;
    alt: string | null;
    asset: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    } | null;
  }> | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: pageBySlugQuery
// Query: *[_type == "page" && slug.current == $slug][0] {    _id,    title,    slug,    mainImage,    body  }
export type PageBySlugQueryResult = {
  _id: string;
  title: string | null;
  slug: Slug | null;
  mainImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  body: BlockContent | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "horse"] | order(name asc) {\n    _id,\n    name,\n    slug,\n    breed,\n    birthYear,\n    status,\n    mainImage\n  }\n': HorsesQueryResult;
    '\n  *[_type == "horse" && slug.current == $slug][0] {\n    _id,\n    name,\n    slug,\n    breed,\n    birthYear,\n    status,\n    mainImage,\n    description,\n    sire,\n    dam,\n    milestones,\n    photos,\n    videos\n  }\n': HorseBySlugQueryResult;
    '\n  *[_type == "horse" && defined(slug.current)] {\n    "slug": slug.current\n  }\n': HorsesSlugsQueryResult;
    '\n  *[_type == "horse" && status == "active"] | order(name asc) [0...3] {\n    _id,\n    name,\n    slug,\n    breed,\n    mainImage\n  }\n': FeaturedHorsesQueryResult;
    '\n  *[_type == "siteSettings"][0] {\n    address,\n    city,\n    phone,\n    email,\n    facebook,\n    instagram,\n    heroImage\n  }\n': SiteSettingsQueryResult;
    '\n  *[_type == "horse" && defined(photos) && count(photos) > 0] | order(name asc) {\n    name,\n    "slug": slug.current,\n    "photos": photos[] {\n      _key,\n      alt,\n      asset\n    }\n  }\n': GalleryQueryResult;
    '\n  *[_type == "page" && slug.current == $slug][0] {\n    _id,\n    title,\n    slug,\n    mainImage,\n    body\n  }\n': PageBySlugQueryResult;
  }
}
